<?php

/**
 * Actionmenu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Actionmenu.php,v 1.4 2011/08/30 16:24:06 proditis Exp $
 */
class Actionmenu extends BaseActionmenu
{
	function setPerm($perm)
	{
		global $PERMS;
		$this->_set('perm',$PERMS[$perm]);
	}

    public function save()
    {
        try
        {
            parent :: save();
        } catch (Exception $e)
        {
            switch ($e->getCode())
            {
                case 23000 :
                case 1062 :
                    parent :: replace();
                    break;
                default :
                    throw $e;
            }
        }
    }
}