<?php

/**
 * Archive
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Archive.php,v 1.1.6.1 2011/09/02 12:03:28 proditis Exp $
 */
class Archive extends BaseArchive
{

}