<?php

/**
 * Ip
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Ip.php,v 1.1.4.1 2011/09/02 12:03:27 proditis Exp $
 */
class Ip extends BaseIp
{
    public function save()
    {
        try
        {
            parent::save();
        } catch (Exception $e)
        {
            switch ($e->getCode())
            {
                case 23000 :
                case 1062 :
                    parent::replace();
                    break;
                default :
                    throw $e;
            }
        }
    }
    
    public function setAddress($address)
    {
        $this->_set('address', ip2long($address));
    }

    public function getTags()
    {
        $v=null;
        foreach($this->_get('IpTag') as $iptag)
          $v[]=$iptag->Tag->name;
        return implode(', ',$v);
    }
    public function setRawaddress($address)
    {
        $this->_set('address', $address);
    }
    public function getAddress()
    {
        return long2ip($this->_get('address'));
    }
    
}