<?php

/**
 * IpTag
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: IpTag.php,v 1.1.2.1 2011/09/02 12:03:28 proditis Exp $
 */
class IpTag extends BaseIpTag
{
    public function save()
    {
        try
        {
            parent::save();
        } catch (Exception $e)
        {
            switch ($e->getCode())
            {
                case 23000 :
                case 1062 :
                    parent::replace();
                    break;
                default :
                    throw $e;
            }
        }
    }
}