<?php

/**
 * Pageaction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Pageaction.php,v 1.5 2011/08/30 16:24:06 proditis Exp $
 */
class Pageaction extends BasePageaction
{
	function setPerm($perm)
	{
		global $PERMS;
		$this->_set('perm',$PERMS[$perm]);
	}
	
	public function getURI()
	{
		$container=$this->_get('tcontainer');
		$module=$this->_get('tmodule');
		$action=$this->_get('taction');
		return gen_uri($container,$module,$action);
	}
    public function save()
    {
        try
        {
            parent :: save();
        } catch (Exception $e)
        {
            switch ($e->getCode())
            {
                case 23000 :
                case 1062 :
                    parent :: replace();
                    break;
                default :
                    throw $e;
            }
        }
    }	
}