<?php

/**
 * Query
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Query.php,v 1.1.2.1 2011/09/02 12:03:27 proditis Exp $
 */
class Query extends BaseQuery
{

}