<?php
/**
 * Translation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Translation.php,v 1.1 2011/08/27 17:37:21 proditis Exp $
 */
class Translation extends BaseTranslation
{
    public function save()
    {
        try
        {
            parent :: save();
        } catch (Exception $e)
        {
            switch ($e->getCode())
            {
                case 23000 :
                case 1062 :
                    parent :: replace();
                    break;
                default :
                    throw $e;
            }
        }
    }
}