# Dockerfile-db for echofish
# docker build -t a0 -f Dockerfile-db ..
# docker run --name echofish-db -e MYSQL_ROOT_PASSWORD=root -p 127.0.0.1:3306:3306 -d a0

# Use MariaDB 10.1 for the base image
FROM mariadb:10.1

# Copy database initialisation scripts
# Note: paths refactored for docker-compose context (..)
COPY ./docker/mycnf-event-scheduler.conf /etc/mysql/conf.d/
COPY ./docker/init.sql /docker-entrypoint-initdb.d/
COPY ./schema/00_echofish-schema.sql /db/
COPY ./schema/echofish-dataonly.sql /db/
COPY ./schema/echofish-functions.sql /db/
COPY ./schema/echofish-triggers.sql /db/
COPY ./schema/echofish-events.sql /db/
COPY ./schema/echofish-procedures.mariadb10.sql /db/

